### ISSUE TITLE
Allow Sass Imports

### ISSUE THREAD

**Issue by finder** [jus/jus#76]
Hello,
I could be misconfiguring something, but I've tried to simplify this as much as possible to test. It seems that jus doesn't support sass imports, so this is probably a feature request. :)

I have a directory structure like (simplified)
.
├── index.html
└── sass
    ├── app
    │   └── _colors.sass
    └── app.sass

app.sass is just a single line:
@import "app/colors"

When I try to visit /sass/app.css I get the error:

```
Error: File to import not found or unreadable: app/colors
Parent style sheet: stdin
  at Object.module.exports.renderSync (/home/finder/.npm-global/lib/node_modules/jus/node_modules/node-sass/lib/index.js:434:16)
  at Stylesheet.render (/home/finder/.npm-global/lib/node_modules/jus/lib/files/stylesheet.js:48:10)
  at Function.server.respondWithFile (/home/finder/.npm-global/lib/node_modules/jus/lib/routes.js:72:19)
  at server.get (/home/finder/.npm-global/lib/node_modules/jus/lib/routes.js:54:12)
  at Layer.handle [as handle_request] (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/layer.js:95:5)
  at next (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/route.js:137:13)
  at Route.dispatch (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/route.js:112:3)
  at Layer.handle [as handle_request] (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/layer.js:95:5)
  at /home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:281:22
  at param (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:354:14)
  at param (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:365:14)
  at Function.process_params (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:410:3)
  at next (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:275:10)
  at /home/finder/.npm-global/lib/node_modules/jus/node_modules/connect-injector/lib/connect-injector.js:163:12
  at Layer.handle [as handle_request] (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:317:13)
  at /home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:284:7
  at Function.process_params (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:335:12)
  at next (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:275:10)
  at logger (/home/finder/.npm-global/lib/node_modules/jus/node_modules/morgan/index.js:144:5)
  at Layer.handle [as handle_request] (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:317:13)
  at /home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:284:7
  at Function.process_params (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:335:12)
  at next (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:275:10)
  at cors (/home/finder/.npm-global/lib/node_modules/jus/node_modules/cors/lib/index.js:188:7)
  at /home/finder/.npm-global/lib/node_modules/jus/node_modules/cors/lib/index.js:224:17
  at originCallback (/home/finder/.npm-global/lib/node_modules/jus/node_modules/cors/lib/index.js:214:15)
  at /home/finder/.npm-global/lib/node_modules/jus/node_modules/cors/lib/index.js:219:13
  at optionsCallback (/home/finder/.npm-global/lib/node_modules/jus/node_modules/cors/lib/index.js:199:9)
  at corsMiddleware (/home/finder/.npm-global/lib/node_modules/jus/node_modules/cors/lib/index.js:204:7)
  at Layer.handle [as handle_request] (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:317:13)
  at /home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:284:7
  at Function.process_params (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:335:12)
  at next (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:275:10)
  at expressInit (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/middleware/init.js:40:5)
  at Layer.handle [as handle_request] (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:317:13)
  at /home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:284:7
  at Function.process_params (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:335:12)
  at next (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:275:10)
  at query (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/middleware/query.js:45:5)
  at Layer.handle [as handle_request] (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:317:13)
  at /home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:284:7
  at Function.process_params (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:335:12)
  at next (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:275:10)
  at Function.handle (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/router/index.js:174:3)
  at Function.handle (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/application.js:174:10)
  at Server.app (/home/finder/.npm-global/lib/node_modules/jus/node_modules/express/lib/express.js:38:9)
  at emitTwo (events.js:125:13)
  at Server.emit (events.js:213:7)
  at parserOnIncoming (_http_server.js:602:12)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
```

**Comment by cscuderi** [comment]
+1 this is a pretty basic feature of Sass... It looks like when you try to import it won't work, but if you import the Sass file you're trying to reference with an extension of .css, it compiles. The downside is, it's using CSS imports which isn't good.
